version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    volumes:
      - db:/var/lib/postgresql/data

  backend:
    container_name: backend
    build: ./backend
    ports:
      - '3007:8080'
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/rails
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    environment: 
      - RAILS_ENV=development
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - DB_HOST=db
    depends_on:
      - db
      - backend

volumes:
  db:
